all:
  hosts:
    windows_vm:
      ansible_host: 52.170.61.200
      ansible_user: azureuser
      ansible_password: "YourP@ssw0rd123!"
      ansible_connection: winrm
      ansible_winrm_transport: basic
      ansible_port: 5985
