---
- name: Install Notepad++ on Windows
  hosts: windows_vm
  tasks:
    - name: Download Notepad++
      win_get_url:
        url: https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.6.4/npp.8.6.4.Installer.x64.exe
        dest: C:\Temp\npp-installer.exe

    - name: Install Notepad++
      win_package:
        path: C:\Temp\npp-installer.exe
        arguments: /S
        state: present
