- name: Test Windows VM via WinRM
  hosts: windows
  gather_facts: no
  tasks:
    - name: Create a folder
      win_file:
        path: C:\Temp\TestFolder
        state: directory

    - name: Write a text file
      win_file:
        path: C:\Temp\TestFolder\hello.txt
        state: touch
